# Generated by Django 4.1.1 on 2022-10-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="test_opposite",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="test_player",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
