# Generated by Django 4.1.1 on 2022-10-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_host",
        ),
        migrations.AddField(
            model_name="user",
            name="lose",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="win",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
